### PR TITLE
feat: added italian translations

### LINKED ISSUE #87: Update Italian translation
Strings that are missing Italian translation

```xml
<string name="settings_step_vibrate_item">Step change vibration</string>
<string name="settings_backup_item">Backup/Restore</string><string name="settings_timer_item">Timer settings</string>
<string name="prepopulate_aero_description">Recipe created by: James Hoffmann Source: https://youtu.be/j6VlT_jUVPc Grind size: For light roast – finer end of medium. The darker you go the more you may prefer to increase the dose and coarsen the grind Temperature: For light roast – brought to a boil and used immediately. For dark roasts – 85–90℃</string>
<string name="prepopulate_aero_step_press">Press the piston gently</string>
<string name="prepopulate_aero_step_piston">Place the piston 1cm into the brewer</string>
<string name="prepopulate_aero_step_piston">Place the piston 1cm into the brewer</string>
<string name="prepopulate_aero_name">AeroPress</string>
<string name="settings_addDefault">Add default recipes</string>
<string name="settings_restore">Restore</string>
<string name="settings_backup">Backup</string>
<string name="step_add_duration_explainer">Step duration determines how long an action will take (in seconds). If you want to create a step that will hold whole recipe till you are read, just leave it empty.</string>
<string name="recipe_details_noTime">Press start to continue</string>
<string name="button_show">Show</string>
<string name="recipe_edit_description_button">Add description</string>
<string name="app_version">App version</string>
<string name="button_continue_editing">Continue editing</string>
<string name="recipe_clone_suffix">%1$s - Copy</string>
<string name="recipe_clone_text">This will create a duplicate of this recipe</string>
<string name="recipe_clone_title">Clone this recipe?</string>
<string name="button_discard">Discard</string>
<string name="recipe_unsaved_text">Do you want to discard them?</string>
<string name="recipe_unsaved_title">You have unsaved changes</string>
```

After you translated them, add them to `app/src/main/res/values-it/strings.xml` and send a PR

Please do not use online translation services for this!

### PR DESCRIPTION
**Pull request by goverdhan07**
# Description
added italian translations

Fixes #87 

## Type of change

- [ ] Bug fix
- [x] New feature

# Checklist:

- [x] I've added new item into [Changelog](docs/Changelog.md) under [Unreleased]
- [x] I've tested the change on device

### CODE REVIEW

**Comment by rozPierog** [comment]
Hey @goverdhan07 thanks for the PR. Do you know Italian or did you use some translation service to translate those strings?

**Comment by goverdhan07** [comment]
> Hey @goverdhan07 thanks for the PR. Do you know Italian or did you use some translation service to translate those strings?

hello @rozPierog, No I dont know Italian, for this I have used google translate. :)

**Comment by rozPierog** [comment]
Thanks for being honest. 
Sorry then I won't accept this PR. If you would like to translate the app to the language you do know, then I would be happy to accept the PR from you!

**Comment by goverdhan07** [comment]
> Thanks for being honest. Sorry then I won't accept this PR. If you would like to translate the app to the language you do know, then I would be happy to accept the PR from you!

Ah! sorry didn't knew about this, nevertheless cool project <3

**Pull request closed without merging**
